apiVersion: v1
kind: Pod
metadata:
  name: kube-scheduler
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: kube-scheduler
      image: registry.k8s.io/kube-scheduler:v1.30.0
      command:
        - kube-scheduler
      args:
        - --kubeconfig=/root/.kube/config
        - --leader-elect=false
        - --v=2
        - --bind-address=0.0.0.0
      volumeMounts:
        - name: config
          mountPath: /root/.kube/
  volumes:
  - name: config
    hostPath:
      path: /root/.kube
