apiVersion: v1
kind: Pod
metadata:
  name: kube-controller-manager
  namespace: kube-system
spec:
  hostNetwork: true
  containers:
    - name: kube-controller-manager
      image: registry.k8s.io/kube-controller-manager:v1.30.0
      command:
        - kube-controller-manager
      args:
        - --kubeconfig=/root/.kube/config
        - --leader-elect=false
        - --service-cluster-ip-range=10.0.0.0/24
        - --cluster-name=kubernetes
        - --root-ca-file=/tmp/ca.crt
        - --service-account-private-key-file=/tmp/sa.key
        - --use-service-account-credentials=true
        - --v=2
      volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: config
          mountPath: /root/.kube/
  volumes:
  - name: tmp
    hostPath:
      path: /tmp
  - name: config
    hostPath:
      path: /root/.kube
