FROM golang:1.25 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /bin/manager main.go

FROM alpine:3.22

WORKDIR /app/

COPY --from=builder /bin/manager /app/manager

CMD ["/app/manager"]
